apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: ips
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-app
  template:
    metadata:
      labels:
        app: mi-app
    spec:
      imagePullSecrets:
        - name: mi-registro-secreto
      containers:
      - name: backend-app
        image: javierub/pr07_infra:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 8080